import { useState, useEffect } from 'react';
import { useFeatures } from '../context/FeatureContext';
import UpgradePrompt from '../components/UpgradePrompt';
import { timeEntriesApi, jobsApi } from '../services/api';

function AnalyticsPage() {
  const { hasFeature, loading: featuresLoading } = useFeatures();
  const [loading, setLoading] = useState(true);
  const [timeEntries, setTimeEntries] = useState([]);
  const [jobs, setJobs] = useState([]);
  const [dateRange, setDateRange] = useState({
    startDate: new Date(new Date().setDate(new Date().getDate() - 30)).toISOString().split('T')[0],
    endDate: new Date().toISOString().split('T')[0],
  });

  useEffect(() => {
    if (hasFeature('COST_ANALYTICS')) {
      loadData();
    }
  }, [dateRange, hasFeature]);

  const loadData = async () => {
    try {
      setLoading(true);
      const [entriesRes, jobsRes] = await Promise.all([
        timeEntriesApi.getAll(dateRange),
        jobsApi.getAll(),
      ]);
      setTimeEntries(entriesRes.data);
      setJobs(jobsRes.data);
    } catch (err) {
      console.error('Failed to load analytics data:', err);
    } finally {
      setLoading(false);
    }
  };

  const setQuickRange = (days) => {
    const end = new Date();
    const start = new Date();
    start.setDate(start.getDate() - days);
    setDateRange({
      startDate: start.toISOString().split('T')[0],
      endDate: end.toISOString().split('T')[0],
    });
  };

  // Calculate analytics data
  const totalHours = timeEntries.reduce((sum, entry) => {
    if (entry.clockOut) {
      const hours = (new Date(entry.clockOut) - new Date(entry.clockIn)) / (1000 * 60 * 60);
      return sum + hours;
    }
    return sum;
  }, 0);

  const avgHourlyRate = 35;
  const totalCost = totalHours * avgHourlyRate;
  const activeJobs = jobs.filter(j => j.status === 'ACTIVE').length;

  const jobStats = jobs.map(job => {
    const jobEntries = timeEntries.filter(e => e.jobId === job.id);
    const hours = jobEntries.reduce((sum, entry) => {
      if (entry.clockOut) {
        return sum + (new Date(entry.clockOut) - new Date(entry.clockIn)) / (1000 * 60 * 60);
      }
      return sum;
    }, 0);
    return { ...job, hours, cost: hours * avgHourlyRate, entries: jobEntries.length };
  }).sort((a, b) => b.hours - a.hours);

  // Generate CSV and download
  const generateCSVFallback = () => {
    const headers = ['Job Site', 'Hours', 'Labor Cost', 'Entries', '% of Total'];
    const rows = jobStats.map(job => [
      job.name,
      job.hours.toFixed(1),
      `$${job.cost.toFixed(2)}`,
      job.entries,
      `${totalHours > 0 ? (job.hours / totalHours * 100).toFixed(1) : 0}%`
    ]);
    
    const csvContent = [
      `Cost Analytics Report: ${dateRange.startDate} to ${dateRange.endDate}`,
      '',
      `Total Hours,${totalHours.toFixed(1)}`,
      `Total Cost,$${totalCost.toFixed(2)}`,
      `Active Jobs,${activeJobs}`,
      `Time Entries,${timeEntries.length}`,
      '',
      headers.join(','),
      ...rows.map(row => row.join(','))
    ].join('\n');
    
    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `cost-analytics-${dateRange.startDate}-to-${dateRange.endDate}.csv`);
    document.body.appendChild(link);
    link.click();
    link.remove();
    window.URL.revokeObjectURL(url);
  };

  const handleExportExcel = async () => {
    try {
      const response = await timeEntriesApi.exportExcel(dateRange);
      const url = window.URL.createObjectURL(new Blob([response.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `cost-analytics-${dateRange.startDate}-to-${dateRange.endDate}.xlsx`);
      document.body.appendChild(link);
      link.click();
      link.remove();
      window.URL.revokeObjectURL(url);
    } catch (err) {
      console.error('Excel export failed, falling back to CSV:', err);
      generateCSVFallback();
    }
  };

  const handleEmailReport = () => {
    const email = prompt('Enter email address to send report:');
    if (!email) return;
    
    const reportLines = [
      'COST ANALYTICS REPORT',
      '=====================',
      '',
      `Period: ${dateRange.startDate} to ${dateRange.endDate}`,
      '',
      'SUMMARY',
      '-------',
      `Total Hours: ${totalHours.toFixed(1)}`,
      `Total Cost: $${totalCost.toFixed(2)}`,
      `Active Jobs: ${activeJobs}`,
      `Time Entries: ${timeEntries.length}`,
      '',
      'BREAKDOWN BY JOB SITE',
      '---------------------',
      ...jobStats.map(job => `${job.name}: ${job.hours.toFixed(1)} hrs - $${job.cost.toFixed(2)}`),
      '',
      'Generated by ApexChronos'
    ];
    
    const subject = encodeURIComponent(`Cost Analytics Report - ${dateRange.startDate} to ${dateRange.endDate}`);
    const body = encodeURIComponent(reportLines.join('\n'));
    window.open(`mailto:${email}?subject=${subject}&body=${body}`);
  };

  if (featuresLoading) {
    return <div style={{ padding: '60px', textAlign: 'center', color: '#888' }}>Loading...</div>;
  }

  if (!hasFeature('COST_ANALYTICS')) {
    return <UpgradePrompt feature="COST_ANALYTICS" requiredPlan="Professional" />;
  }

  return (
    <div style={{ padding: '30px' }}>
      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '30px', flexWrap: 'wrap', gap: '20px' }}>
        <div>
          <h1 style={{ fontSize: '32px', background: 'linear-gradient(135deg, #a855f7, #ec4899)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', marginBottom: '5px' }}>
            💰 Cost Analytics
          </h1>
          <p style={{ color: '#888' }}>Track labor costs by job site in real-time</p>
        </div>
        
        <div style={{ display: 'flex', alignItems: 'center', gap: '10px', flexWrap: 'wrap' }}>
          {/* Export Buttons */}
          <button
            onClick={handleExportExcel}
            style={{ 
              background: 'linear-gradient(135deg, #22c55e, #16a34a)', 
              border: 'none', 
              color: '#fff', 
              padding: '10px 20px', 
              borderRadius: '10px', 
              cursor: 'pointer', 
              fontWeight: '600', 
              display: 'flex', 
              alignItems: 'center', 
              gap: '8px',
              transition: 'transform 0.2s, box-shadow 0.2s'
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.transform = 'translateY(-2px)';
              e.currentTarget.style.boxShadow = '0 8px 25px rgba(34, 197, 94, 0.4)';
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.transform = 'translateY(0)';
              e.currentTarget.style.boxShadow = 'none';
            }}
          >
            📊 Export Excel
          </button>
          <button
            onClick={handleEmailReport}
            style={{ 
              background: 'linear-gradient(135deg, #3b82f6, #2563eb)', 
              border: 'none', 
              color: '#fff', 
              padding: '10px 20px', 
              borderRadius: '10px', 
              cursor: 'pointer', 
              fontWeight: '600', 
              display: 'flex', 
              alignItems: 'center', 
              gap: '8px',
              transition: 'transform 0.2s, box-shadow 0.2s'
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.transform = 'translateY(-2px)';
              e.currentTarget.style.boxShadow = '0 8px 25px rgba(59, 130, 246, 0.4)';
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.transform = 'translateY(0)';
              e.currentTarget.style.boxShadow = 'none';
            }}
          >
            📧 Email Report
          </button>
          
          {/* Quick Date Filters */}
          <button 
            onClick={() => setQuickRange(7)} 
            style={{ 
              background: 'rgba(255,255,255,0.1)', 
              border: 'none', 
              color: '#ccc', 
              padding: '10px 16px', 
              borderRadius: '8px', 
              cursor: 'pointer',
              transition: 'background 0.2s'
            }}
            onMouseEnter={(e) => e.currentTarget.style.background = 'rgba(255,255,255,0.2)'}
            onMouseLeave={(e) => e.currentTarget.style.background = 'rgba(255,255,255,0.1)'}
          >
            7 Days
          </button>
          <button 
            onClick={() => setQuickRange(30)} 
            style={{ 
              background: 'rgba(255,255,255,0.1)', 
              border: 'none', 
              color: '#ccc', 
              padding: '10px 16px', 
              borderRadius: '8px', 
              cursor: 'pointer',
              transition: 'background 0.2s'
            }}
            onMouseEnter={(e) => e.currentTarget.style.background = 'rgba(255,255,255,0.2)'}
            onMouseLeave={(e) => e.currentTarget.style.background = 'rgba(255,255,255,0.1)'}
          >
            30 Days
          </button>
          <button 
            onClick={() => setQuickRange(90)} 
            style={{ 
              background: 'rgba(255,255,255,0.1)', 
              border: 'none', 
              color: '#ccc', 
              padding: '10px 16px', 
              borderRadius: '8px', 
              cursor: 'pointer',
              transition: 'background 0.2s'
            }}
            onMouseEnter={(e) => e.currentTarget.style.background = 'rgba(255,255,255,0.2)'}
            onMouseLeave={(e) => e.currentTarget.style.background = 'rgba(255,255,255,0.1)'}
          >
            90 Days
          </button>
          
          {/* Date Range Picker */}
          <div style={{ 
            display: 'flex', 
            alignItems: 'center', 
            gap: '8px', 
            background: 'rgba(255,255,255,0.05)', 
            padding: '8px 12px', 
            borderRadius: '8px', 
            border: '1px solid rgba(255,255,255,0.1)' 
          }}>
            <span>📅</span>
            <input 
              type="date" 
              value={dateRange.startDate} 
              onChange={(e) => setDateRange({ ...dateRange, startDate: e.target.value })} 
              style={{ background: 'transparent', border: 'none', color: '#fff', cursor: 'pointer' }} 
            />
            <span style={{ color: '#888' }}>to</span>
            <input 
              type="date" 
              value={dateRange.endDate} 
              onChange={(e) => setDateRange({ ...dateRange, endDate: e.target.value })} 
              style={{ background: 'transparent', border: 'none', color: '#fff', cursor: 'pointer' }} 
            />
          </div>
        </div>
      </div>

      {loading ? (
        <div style={{ textAlign: 'center', padding: '80px' }}>
          <div style={{
            width: '50px',
            height: '50px',
            border: '4px solid rgba(168, 85, 247, 0.2)',
            borderTopColor: '#a855f7',
            borderRadius: '50%',
            animation: 'spin 1s linear infinite',
            margin: '0 auto 20px'
          }}></div>
          <p style={{ color: '#888' }}>Loading analytics...</p>
          <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
        </div>
      ) : (
        <>
          {/* Stats Grid */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '20px', marginBottom: '30px' }}>
            <div style={{ 
              background: 'rgba(255,255,255,0.02)', 
              border: '1px solid rgba(255,255,255,0.1)', 
              borderRadius: '16px', 
              padding: '25px', 
              display: 'flex', 
              alignItems: 'center', 
              gap: '20px',
              transition: 'transform 0.2s, border-color 0.2s'
            }}>
              <div style={{ 
                width: '60px', 
                height: '60px', 
                borderRadius: '16px', 
                background: 'rgba(59, 130, 246, 0.15)', 
                display: 'flex', 
                alignItems: 'center', 
                justifyContent: 'center', 
                fontSize: '28px' 
              }}>⏱️</div>
              <div>
                <p style={{ color: '#888', fontSize: '12px', textTransform: 'uppercase', margin: 0 }}>Total Hours</p>
                <p style={{ fontSize: '32px', fontWeight: '700', color: '#3b82f6', margin: '5px 0' }}>{totalHours.toFixed(1)}</p>
                <p style={{ color: '#666', fontSize: '12px', margin: 0 }}>hours worked</p>
              </div>
            </div>
            
            <div style={{ 
              background: 'rgba(255,255,255,0.02)', 
              border: '1px solid rgba(255,255,255,0.1)', 
              borderRadius: '16px', 
              padding: '25px', 
              display: 'flex', 
              alignItems: 'center', 
              gap: '20px' 
            }}>
              <div style={{ 
                width: '60px', 
                height: '60px', 
                borderRadius: '16px', 
                background: 'rgba(34, 197, 94, 0.15)', 
                display: 'flex', 
                alignItems: 'center', 
                justifyContent: 'center', 
                fontSize: '28px' 
              }}>💵</div>
              <div>
                <p style={{ color: '#888', fontSize: '12px', textTransform: 'uppercase', margin: 0 }}>Total Cost</p>
                <p style={{ fontSize: '32px', fontWeight: '700', color: '#22c55e', margin: '5px 0' }}>${totalCost.toFixed(2)}</p>
                <p style={{ color: '#666', fontSize: '12px', margin: 0 }}>at ${avgHourlyRate}/hr</p>
              </div>
            </div>
            
            <div style={{ 
              background: 'rgba(255,255,255,0.02)', 
              border: '1px solid rgba(255,255,255,0.1)', 
              borderRadius: '16px', 
              padding: '25px', 
              display: 'flex', 
              alignItems: 'center', 
              gap: '20px' 
            }}>
              <div style={{ 
                width: '60px', 
                height: '60px', 
                borderRadius: '16px', 
                background: 'rgba(168, 85, 247, 0.15)', 
                display: 'flex', 
                alignItems: 'center', 
                justifyContent: 'center', 
                fontSize: '28px' 
              }}>🏗️</div>
              <div>
                <p style={{ color: '#888', fontSize: '12px', textTransform: 'uppercase', margin: 0 }}>Active Jobs</p>
                <p style={{ fontSize: '32px', fontWeight: '700', color: '#a855f7', margin: '5px 0' }}>{activeJobs}</p>
                <p style={{ color: '#666', fontSize: '12px', margin: 0 }}>job sites</p>
              </div>
            </div>
            
            <div style={{ 
              background: 'rgba(255,255,255,0.02)', 
              border: '1px solid rgba(255,255,255,0.1)', 
              borderRadius: '16px', 
              padding: '25px', 
              display: 'flex', 
              alignItems: 'center', 
              gap: '20px' 
            }}>
              <div style={{ 
                width: '60px', 
                height: '60px', 
                borderRadius: '16px', 
                background: 'rgba(245, 158, 11, 0.15)', 
                display: 'flex', 
                alignItems: 'center', 
                justifyContent: 'center', 
                fontSize: '28px' 
              }}>📋</div>
              <div>
                <p style={{ color: '#888', fontSize: '12px', textTransform: 'uppercase', margin: 0 }}>Time Entries</p>
                <p style={{ fontSize: '32px', fontWeight: '700', color: '#f59e0b', margin: '5px 0' }}>{timeEntries.length}</p>
                <p style={{ color: '#666', fontSize: '12px', margin: 0 }}>clock ins</p>
              </div>
            </div>
          </div>

          {/* Cost Breakdown Table */}
          <div style={{ 
            background: 'rgba(255,255,255,0.02)', 
            border: '1px solid rgba(255,255,255,0.1)', 
            borderRadius: '16px', 
            padding: '25px', 
            marginBottom: '30px' 
          }}>
            <h2 style={{ color: '#fff', fontSize: '20px', marginBottom: '20px' }}>📊 Cost by Job Site</h2>
            
            <div style={{ overflowX: 'auto' }}>
              <table style={{ width: '100%', borderCollapse: 'collapse' }}>
                <thead>
                  <tr>
                    <th style={{ textAlign: 'left', color: '#888', fontSize: '12px', fontWeight: '600', textTransform: 'uppercase', padding: '15px', borderBottom: '1px solid rgba(255,255,255,0.1)' }}>Job Site</th>
                    <th style={{ textAlign: 'left', color: '#888', fontSize: '12px', fontWeight: '600', textTransform: 'uppercase', padding: '15px', borderBottom: '1px solid rgba(255,255,255,0.1)' }}>Hours</th>
                    <th style={{ textAlign: 'left', color: '#888', fontSize: '12px', fontWeight: '600', textTransform: 'uppercase', padding: '15px', borderBottom: '1px solid rgba(255,255,255,0.1)' }}>Labor Cost</th>
                    <th style={{ textAlign: 'left', color: '#888', fontSize: '12px', fontWeight: '600', textTransform: 'uppercase', padding: '15px', borderBottom: '1px solid rgba(255,255,255,0.1)' }}>Entries</th>
                    <th style={{ textAlign: 'left', color: '#888', fontSize: '12px', fontWeight: '600', textTransform: 'uppercase', padding: '15px', borderBottom: '1px solid rgba(255,255,255,0.1)' }}>% of Total</th>
                  </tr>
                </thead>
                <tbody>
                  {jobStats.map(job => (
                    <tr key={job.id} style={{ transition: 'background 0.2s' }}>
                      <td style={{ padding: '18px 15px', color: '#fff', fontWeight: '500', borderBottom: '1px solid rgba(255,255,255,0.05)' }}>
                        🏢 {job.name}
                      </td>
                      <td style={{ padding: '18px 15px', color: '#ccc', borderBottom: '1px solid rgba(255,255,255,0.05)' }}>
                        {job.hours.toFixed(1)} hrs
                      </td>
                      <td style={{ padding: '18px 15px', color: '#22c55e', fontWeight: '600', borderBottom: '1px solid rgba(255,255,255,0.05)' }}>
                        ${job.cost.toFixed(2)}
                      </td>
                      <td style={{ padding: '18px 15px', color: '#ccc', borderBottom: '1px solid rgba(255,255,255,0.05)' }}>
                        {job.entries}
                      </td>
                      <td style={{ padding: '18px 15px', borderBottom: '1px solid rgba(255,255,255,0.05)' }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                          <div style={{ width: '100px', height: '8px', background: 'rgba(255,255,255,0.1)', borderRadius: '4px', overflow: 'hidden' }}>
                            <div style={{ 
                              width: `${totalHours > 0 ? (job.hours / totalHours * 100) : 0}%`, 
                              height: '100%', 
                              background: 'linear-gradient(135deg, #a855f7, #ec4899)', 
                              borderRadius: '4px',
                              transition: 'width 0.5s ease'
                            }}></div>
                          </div>
                          <span style={{ color: '#888', fontSize: '13px', minWidth: '45px' }}>
                            {totalHours > 0 ? (job.hours / totalHours * 100).toFixed(1) : 0}%
                          </span>
                        </div>
                      </td>
                    </tr>
                  ))}
                  {jobStats.length === 0 && (
                    <tr>
                      <td colSpan={5} style={{ textAlign: 'center', padding: '50px', color: '#666' }}>
                        <span style={{ fontSize: '40px', display: 'block', marginBottom: '10px' }}>📭</span>
                        No data for selected period
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>

          {/* Quick Insights */}
          <div style={{ 
            background: 'linear-gradient(135deg, rgba(168, 85, 247, 0.1), rgba(236, 72, 153, 0.05))', 
            border: '1px solid rgba(168, 85, 247, 0.2)', 
            borderRadius: '16px', 
            padding: '25px' 
          }}>
            <h2 style={{ color: '#fff', fontSize: '20px', marginBottom: '20px' }}>💡 Quick Insights</h2>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '20px' }}>
              <div style={{ 
                background: 'rgba(255,255,255,0.05)', 
                borderRadius: '12px', 
                padding: '20px', 
                display: 'flex', 
                alignItems: 'center', 
                gap: '15px' 
              }}>
                <span style={{ fontSize: '28px' }}>📈</span>
                <div>
                  <p style={{ color: '#888', fontSize: '13px', margin: 0 }}>Avg Daily Cost</p>
                  <p style={{ color: '#fff', fontSize: '18px', fontWeight: '600', margin: 0 }}>
                    ${(totalCost / 30).toFixed(2)}/day
                  </p>
                </div>
              </div>
              <div style={{ 
                background: 'rgba(255,255,255,0.05)', 
                borderRadius: '12px', 
                padding: '20px', 
                display: 'flex', 
                alignItems: 'center', 
                gap: '15px' 
              }}>
                <span style={{ fontSize: '28px' }}>👷</span>
                <div>
                  <p style={{ color: '#888', fontSize: '13px', margin: 0 }}>Avg Hours/Entry</p>
                  <p style={{ color: '#fff', fontSize: '18px', fontWeight: '600', margin: 0 }}>
                    {timeEntries.length > 0 ? (totalHours / timeEntries.length).toFixed(1) : 0} hrs
                  </p>
                </div>
              </div>
              <div style={{ 
                background: 'rgba(255,255,255,0.05)', 
                borderRadius: '12px', 
                padding: '20px', 
                display: 'flex', 
                alignItems: 'center', 
                gap: '15px' 
              }}>
                <span style={{ fontSize: '28px' }}>🎯</span>
                <div>
                  <p style={{ color: '#888', fontSize: '13px', margin: 0 }}>Top Job Site</p>
                  <p style={{ color: '#fff', fontSize: '18px', fontWeight: '600', margin: 0 }}>
                    {jobStats[0]?.name || 'N/A'}
                  </p>
                </div>
              </div>
            </div>
          </div>
        </>
      )}
    </div>
  );
}

export default AnalyticsPage;